version: "3.9"

networks:
  purple_net:
    external: true

services:
  freqtrade:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: purple_freqtrade
    restart: unless-stopped
    networks:
      - purple_net
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/tradesv3_live_testnet.sqlite
      --config /freqtrade/user_data/config.json
      --strategy PurpleRSIEMA